# Generated by Django 5.2.17 on 2026-09-28 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('event_type', models.CharField(db_index=True, help_text='Name of the domain event, e.g. reservation.created', max_length=100)),
                ('aggregate_type', models.CharField(db_index=True, help_text='Type of the aggregate root, e.g. reservation, place', max_length=50)),
                ('aggregate_id', models.UUIDField(db_index=True, help_text='ID of the aggregate root entity')),
                ('payload', models.JSONField(help_text='Full event payload serialized as JSON')),
                ('published', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been published to Redis Streams')),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when event was published', null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['published', 'created_at'], name='outbox_pub_created_idx')],
            },
        ),
    ]
