# Generated by Django 5.2.17 on 2026-10-03 08:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        CreateExtension("pg_trgm"),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=255)),
                (
                    "normalized_name",
                    models.CharField(
                        help_text="Lowercase, stripped name; derived from name, used for matching and fuzzy search",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Globally unique URL-friendly identifier", unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Primary category, e.g. 'restaurant', 'hotel', 'attraction'",
                        max_length=50,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="More specific category, e.g. 'italian_restaurant', 'boutique_hotel'",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Free text description"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="", help_text="Full address string"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="City name", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="State/province",
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", help_text="Country", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Postal/ZIP code",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="PostGIS geography point (WGS84 lat/lng)",
                        spatial_index=False,
                        srid=4326,
                    ),
                ),
                (
                    "h3_index_res8",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Precomputed H3 index at resolution 8",
                        max_length=16,
                    ),
                ),
                (
                    "h3_index_res9",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Precomputed H3 index at resolution 9",
                        max_length=16,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Aggregate rating 0.00 - 5.00 (null until enriched by a rated provider)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        default=0, help_text="Total reviews across providers"
                    ),
                ),
                (
                    "price_level",
                    models.IntegerField(
                        blank=True,
                        help_text="1-4 ($ to $$$$, null when unknown)",
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Official website URL",
                        max_length=500,
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Structured hours, e.g. {"monday": [{"open": "09:00", "close": "22:00"}]}',
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of photo URLs"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific extra data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete flag; inactive places are hidden from search",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Data quality flag (manually or automatically verified)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "db_table": "places",
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="idx_places_location_gist"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["normalized_name"],
                        name="idx_places_name_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    models.Index(fields=["category"], name="idx_places_category"),
                    models.Index(fields=["city"], name="idx_places_city"),
                    models.Index(fields=["rating"], name="idx_places_rating"),
                    models.Index(fields=["price_level"], name="idx_places_price_level"),
                    models.Index(fields=["h3_index_res8"], name="idx_places_h3_res8"),
                    models.Index(fields=["h3_index_res9"], name="idx_places_h3_res9"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlaceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable category name, e.g. 'Italian Restaurant'",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly category identifier", unique=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier for UI rendering",
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (null for top-level categories)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="places.placecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Category",
                "verbose_name_plural": "Place Categories",
                "db_table": "place_categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'outdoor_seating', 'pet_friendly', 'live_music'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Places carrying this tag",
                        related_name="tags",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="PlaceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OVERTURE", "Overture Maps"),
                            ("FOURSQUARE", "Foursquare"),
                            ("GOOGLE", "Google Places"),
                            ("SWIGGY", "Swiggy"),
                        ],
                        help_text="Data provider identifier",
                        max_length=50,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        help_text="ID of the place in the provider's system",
                        max_length=255,
                    ),
                ),
                (
                    "provider_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to the provider's listing",
                        max_length=500,
                    ),
                ),
                (
                    "provider_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw provider response (kept for audit/re-ingestion)",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Match confidence 0.00 - 1.00",
                        max_digits=3,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last enrichment from this provider",
                        null=True,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        help_text="Canonical place this source feeds",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Source",
                "verbose_name_plural": "Place Sources",
                "db_table": "place_sources",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_id"),
                        name="uniq_place_source_provider_id",
                    )
                ],
            },
        ),
    ]
