# Generated by Django 5.2.17 on 2026-09-28 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='User email address (used for login)', max_length=255, unique=True)),
                ('username', models.CharField(blank=True, help_text='Optional display name or handle', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional contact phone number', max_length=20)),
                ('avatar_url', models.URLField(blank=True, default='', help_text="URL to user's profile avatar", max_length=500)),
                ('preferred_language', models.CharField(default='en', help_text="Preferred interface language code (e.g. 'en', 'hi')", max_length=10)),
                ('location_sharing_consent', models.BooleanField(default=False, help_text='Explicit consent granted by user for browser/device location sharing (City Pulse)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text="List of preferred categories (e.g. ['restaurants', 'cafes', 'museums'])")),
                ('preferred_cuisines', models.JSONField(blank=True, default=list, help_text="List of preferred cuisines (e.g. ['italian', 'coastal', 'north_indian'])")),
                ('price_preference', models.IntegerField(default=2, help_text='Budget preference: 1 (Budget), 2 (Moderate), 3 (Upscale), 4 (Fine Dining)')),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, help_text="Dietary flags (e.g. ['vegetarian', 'vegan', 'halal', 'gluten_free'])")),
                ('max_walking_distance_m', models.IntegerField(default=2000, help_text='Maximum preferred walking distance in meters')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
