# Generated by Django 5.2.17 on 2026-10-03 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "h3_index",
                    models.CharField(
                        help_text="H3 cell index this context describes", max_length=16
                    ),
                ),
                (
                    "time_bucket",
                    models.DateTimeField(
                        help_text="Start of the time bucket this context was computed for (e.g. top of hour)"
                    ),
                ),
                (
                    "activity_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Aggregated activity metrics for the bucket (check-ins, saves, searches, …)",
                    ),
                ),
                (
                    "top_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Currently popular categories in this cell (ranked list of {category, score})",
                    ),
                ),
                (
                    "top_places",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top places in this cell (ranked list of {place_id, name, score})",
                    ),
                ),
                (
                    "weather_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the current/expected weather for the cell (from WeatherData)",
                    ),
                ),
                (
                    "llm_summary",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated natural-language description of the area for this bucket",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True,
                        help_text="LLM provider/model that produced llm_summary",
                        max_length=50,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="TTL — context is stale and must be regenerated after this time"
                    ),
                ),
            ],
            options={
                "db_table": "geo_areacontext",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("h3_index", "time_bucket"),
                        name="uniq_geoacontext_h3_bucket",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Dense integer primary key (time-series volume; see model docstring)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "h3_index",
                    models.CharField(
                        help_text="H3 cell index at resolution 7 (coarser than Place's res8/9 — weather grid)",
                        max_length=16,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Observation or forecast time (UTC) this row describes"
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Temperature in degrees Celsius",
                        max_digits=5,
                    ),
                ),
                (
                    "precipitation_probability",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Probability of precipitation, 0-100 (percent)",
                        max_digits=5,
                    ),
                ),
                (
                    "precipitation_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total precipitation in millimetres",
                        max_digits=5,
                    ),
                ),
                (
                    "wind_speed_kmh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wind speed in kilometres per hour",
                        max_digits=5,
                    ),
                ),
                (
                    "humidity_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Relative humidity, 0-100 (percent)",
                        max_digits=5,
                    ),
                ),
                (
                    "weather_code",
                    models.IntegerField(
                        help_text="WMO weather interpretation code (0=clear, 1-3=partly cloudy, 45/48=fog, 51+=rain, 61+=drizzle/snow…)"
                    ),
                ),
                (
                    "is_forecast",
                    models.BooleanField(
                        default=False,
                        help_text="True if this row is a forecast, False if an observation",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="open_meteo",
                        help_text="Upstream weather provider identifier",
                        max_length=50,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the provider response was fetched and stored",
                    ),
                ),
            ],
            options={
                "db_table": "geo_weatherdata",
                "indexes": [
                    models.Index(
                        fields=["h3_index", "timestamp"], name="idx_geoweather_h3_ts"
                    )
                ],
            },
        ),
    ]
