# Generated by Django 5.2.17 on 2026-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="weatherdata",
            constraint=models.UniqueConstraint(
                fields=("h3_index", "timestamp", "source", "is_forecast"),
                name="uniq_geo_weather_h3_ts_src_fc",
            ),
        ),
    ]
