# Generated by Django 5.2.17 on 2026-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_weatherdata_uniq_geo_weather_h3_ts_src_fc"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQualityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Dense integer primary key (time-series volume; see model docstring)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "h3_index",
                    models.CharField(
                        help_text="H3 cell index at resolution 7 (weather/AQ grid)",
                        max_length=16,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Observation or forecast time (UTC) this row describes"
                    ),
                ),
                (
                    "us_aqi",
                    models.IntegerField(
                        blank=True,
                        help_text="US Air Quality Index (0-500; null when the cell is outside coverage)",
                        null=True,
                    ),
                ),
                (
                    "pm2_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fine particulate matter ≤2.5µm, µg/m³",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pm10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Particulate matter ≤10µm, µg/m³",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ozone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ground-level ozone O3, µg/m³",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "nitrogen_dioxide",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nitrogen dioxide NO2, µg/m³",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "carbon_monoxide",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Carbon monoxide CO, mg/m³",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="open_meteo_aq",
                        help_text="Upstream air-quality provider identifier",
                        max_length=50,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the provider response was fetched and stored",
                    ),
                ),
            ],
            options={
                "db_table": "geo_airqualitydata",
                "indexes": [
                    models.Index(
                        fields=["h3_index", "timestamp"], name="idx_geoaq_h3_ts"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("h3_index", "timestamp", "source"),
                        name="uniq_geo_aq_h3_ts_src",
                    )
                ],
            },
        ),
    ]
