# Generated by Django 5.2.17 on 2026-10-07 05:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_airqualitydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, spatial_index=False, srid=4326
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("nominatim", "Nominatim/OSM"),
                            ("geojson", "GeoJSON file"),
                            ("bbox", "Rectangle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "relation/3165948"',
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "geo_cities",
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["boundary"], name="idx_geocity_boundary_gist"
                    )
                ],
            },
        ),
    ]
