# Generated by Django 5.2.17 on 2026-10-06 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OVERTURE", "Overture Maps"),
                            ("FOURSQUARE", "Foursquare"),
                            ("GOOGLE", "Google Places"),
                            ("SWIGGY", "Swiggy"),
                        ],
                        help_text="Data provider identifier (single source of truth from PlaceSource)",
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_import", "Full Import"),
                            ("incremental", "Incremental"),
                            ("enrichment", "Enrichment"),
                        ],
                        default="full_import",
                        help_text="Type of ingestion job",
                        max_length=30,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Geographic scope: city:Mumbai | bbox:w,s,e,n | fixture:<path>",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(
                        default=0, help_text="Total records fetched/identified"
                    ),
                ),
                (
                    "processed_records",
                    models.IntegerField(
                        default=0, help_text="Total records processed so far"
                    ),
                ),
                (
                    "created_records",
                    models.IntegerField(default=0, help_text="New records created"),
                ),
                (
                    "updated_records",
                    models.IntegerField(
                        default=0, help_text="Existing records updated"
                    ),
                ),
                (
                    "skipped_records",
                    models.IntegerField(
                        default=0, help_text="Records skipped (unnamed, invalid, etc.)"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Number of errors encountered"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution finished", null=True
                    ),
                ),
                (
                    "error_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Last 100 error entries: [{'where': ..., 'error': ...}]",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Job",
                "verbose_name_plural": "Ingestion Jobs",
                "db_table": "ingestion_jobs",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="idx_ingjob_status_created",
                    ),
                    models.Index(
                        fields=["provider", "job_type", "status"],
                        name="idx_ingjob_prov_type_status",
                    ),
                ],
            },
        ),
    ]
